repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0-1
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: .bumpversion.cfg
    - id: check-merge-conflict
    #- id: check-added-large-files - temp disabled, doesnt seem to work anymore
    - id: check-yaml
    - id: check-json
    - id: pretty-format-json
      args: ["--autofix"]
      exclude: slack.json
