---

# Sample advanced CircleCI configuration: https://github.com/transcom/mymove/blob/master/.circleci/config.yml

version: 2.1
jobs:
  build:
    working_directory: ~/src
    docker:
      - image: hbpmip/docker-compose-for-ci:18.09-1
    environment:
       - CIRCLECI: true
    steps:
      - setup_remote_docker:
          version: 18.06.0-ce
      - checkout
      - restore_cache:
          keys:
            - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
      - run:
          name: "Install requirements"
          command: |
            docker --version
            pre-commit install
      - run:
          name: "Validate code quality"
          command: |
            pre-commit run --all-files
      - save_cache:
          key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          paths:
            - ~/.cache/pre-commit
      - run:
          name: "Build the project"
          command: ./build.sh
      - run:
          name: "Extract the test results from the build image"
          command: |
            mkdir -p test-results/unit-tests/
            docker tag $(docker images --filter "label=build=true" -q | head -n1) wokenbuild:latest
            id=$(docker create wokenbuild)
            docker cp ${id}:/build/target/test-reports/ .
            cp ./test-reports/TEST-*.xml ./test-results/unit-tests/
            docker rm -vf $id
      - run:
          name: "Run integration tests"
          command: ./tests/ci.sh --all
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: test-results/
          destination: test-results
      - store_artifacts:
          path: responses/
          destination: responses
      - store_artifacts:
          path: logs/
          destination: logs
